// Code generated by command: go run asm.go -out add.s -stubs add.go. DO NOT EDIT.

#include "textflag.h"

// func Add(x *Float32x4, y *Float32x4, r *Float32x4)
// Requires: SSE
TEXT ·Add(SB), NOSPLIT, $0-24
	MOVQ   x+0(FP), AX
	MOVQ   y+8(FP), CX
	MOVQ   r+16(FP), DX
	MOVUPS (AX), X0
	MOVUPS (CX), X1
	ADDPS  X0, X1
	MOVAPS X1, (DX)
	RET
	